// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function ChatInput(props) {
  var onSubmit = props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var handleInputChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setText(function (_prev) {
          return value;
        });
  };
  var handleSendClick = function (param) {
    if (text !== "") {
      onSubmit(text);
      return setText(function (_prev) {
                  return "";
                });
    }
    
  };
  var handleKeyDown = function ($$event) {
    if ($$event.key === "Enter" && text !== "") {
      $$event.preventDefault();
      onSubmit(text);
      return setText(function (_prev) {
                  return "";
                });
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("input", {
                      className: "flex-1 px-4 py-2 rounded-md border border-gray-300 focus:ring-2 focus:ring-blue-500 outline-none text-gray-700",
                      placeholder: "Type a message...",
                      type: "text",
                      value: text,
                      onKeyDown: handleKeyDown,
                      onChange: handleInputChange
                    }),
                JsxRuntime.jsx("button", {
                      children: "Send",
                      className: "ml-3 px-4 py-2 rounded-md text-white font-medium " + (
                        text === "" ? "bg-gray-400 cursor-not-allowed" : "bg-blue-500 hover:bg-blue-600"
                      ),
                      disabled: text === "",
                      onClick: handleSendClick
                    })
              ],
              className: "flex items-center bg-gray-100 p-4 rounded-lg shadow-md"
            });
}

var make = ChatInput;

export {
  make ,
}
/* react Not a pure module */
