// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Login(props) {
  var onSubmit = props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setUsername = match[1];
  var username = match[0];
  var handleInputChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setUsername(function (_prev) {
          return value;
        });
  };
  var handleButtonClick = function (param) {
    if (username !== "") {
      onSubmit(username);
      return setUsername(function (_prev) {
                  return "";
                });
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Enter Your Username",
                      className: "card-title text-center mb-4"
                    }),
                JsxRuntime.jsx("input", {
                      className: "input input-bordered w-full mb-4",
                      placeholder: "Username",
                      type: "text",
                      value: username,
                      onChange: handleInputChange
                    }),
                JsxRuntime.jsx("button", {
                      children: "Login",
                      className: "btn btn-primary w-full",
                      onClick: handleButtonClick
                    })
              ],
              className: "card bg-neutral text-neutral-content p-4 rounded-lg"
            });
}

var make = Login;

export {
  make ,
}
/* react Not a pure module */
