// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bytes from "rescript/lib/es6/bytes.js";
import * as Random from "rescript/lib/es6/random.js";

Random.self_init();

function randomnessSetup() {
  console.log("randomnessSetup called");
}

function generateKeypair() {
  console.log("generateKeypair called");
  return [
          String(Random.$$int(100)),
          String(Random.$$int(100))
        ];
}

function generateAndEncryptSharedKey(theirPubKey) {
  console.log("generateAndEncryptSharedKey called with public key", theirPubKey);
  var sharedKey = String(Random.$$int(100));
  return [
          sharedKey,
          sharedKey
        ];
}

function decryptSharedKey(myPrivKey, cipher) {
  console.log("decryptSharedKey called");
  return cipher;
}

function encryptMessage(sharedKey, message) {
  console.log("encryptMessage called with shared key and message", sharedKey, Bytes.to_string(message));
  return [
          String(Random.$$int(100)),
          Bytes.to_string(message)
        ];
}

function decryptMessage(sharedKey, nonce, cipher) {
  console.log("decryptMessage called");
  return Bytes.of_string(cipher);
}

export {
  randomnessSetup ,
  generateKeypair ,
  generateAndEncryptSharedKey ,
  decryptSharedKey ,
  encryptMessage ,
  decryptMessage ,
}
/*  Not a pure module */
